name: Build and test Android app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build app
        run: ./gradlew build
      - name: Build APK
        run: ./gradlew assembleDebug 
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
           name: debug-apk
           path: app/build/outputs/apk/debug/actionbuild.apk

      - name: Run tests
        run: ./gradlew testDebug
        
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run unit tests
        run: ./gradlew test
        
              # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
