name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Choose the appropriate Java version for your project

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug  # Use assembleRelease if you want a release build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug  # You can change this to any desired name
          path: app/build/outputs/apk/debug/app-debug.apk  # Path to the generated APK
